### ISSUE TITLE
Support correct spelling of "algorithm" for all parameters

### ISSUE THREAD

**Issue by brownstein** [auth0/node-xml-encryption#17]
Currently, the encrypt function requires a parameter called "keyEncryptionAlgorighm". This should be "keyEncryptionAlgorithm" to match the spelling of "algorithm" elsewhere, but given that a breaking change would be madness, the API should support both spellings.

**Comment by gkwang** [comment]
This will be fixed as a breaking change through https://github.com/auth0/node-xml-encryption/pull/60 under v1.0.0 release.
