### ISSUE TITLE
tripledes-cbc decryption does not contain setAutoPadding(false); resulting in some decryptions failing

### ISSUE THREAD

**Issue by bensimian** [auth0/node-xml-encryption#23]
Any reason why des-ede3-cbc does not have setAutoPadding to false. This fails some of the decryption. If setAutoPadding to false results in all decryption working. perhaps allow this to be in options?

**Comment by bensimian** [comment]
+1

**Comment by xdmnl** [comment]
@siacomuzzi any news about this issue? There are multiple PR pending trying to solve it.

**Comment by siacomuzzi** [comment]
done:
* PR: https://github.com/auth0/node-xml-encryption/pull/20
* npm: `xml-encryption@0.10.0`

sorry for the delay
