### ISSUE TITLE
wish: keep a changelog

### ISSUE THREAD

**Issue by markstos** [auth0/node-xml-encryption#32]
It's helpful to have a clear description of what's changing between releases, especially for a security/crypto related module. 

http://keepachangelog.com/ is a good resource.

Alternately, you could use the Github "releases" feature to have release notes appear here:

https://github.com/auth0/node-xml-encryption/releases

Using the `hub` Git CLI, integration, it's easy to use `hub release create` and add some notes about the key bits that changed.

**Comment by gkwang** [comment]
We've added the changelogs in https://github.com/auth0/node-xml-encryption/releases. Thanks for the suggestion.
