### ISSUE TITLE
broken travis builds - mocha version needs pinned, or minimum node version increased

### ISSUE THREAD

**Issue by hauntingEcho** [auth0/node-xml-encryption#35]
Mocha dropped support for unmaintained versions of Node (<4) on their version 4:

https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#400--2017-10-02

this is causing some of the pending pull requests (such as #34 ) to have incorrect build failures, and can be fixed by pinning mocha's version (^3.5.3) or by increasing the minimum node version (>=4.0.0) and the version specified for Travis to drop support for versions which the Node devs no longer support.

**Comment by iamcdonald** [comment]
Any movement on this?
It seems there are now a few PR's building up in need of a decision.

**Comment by hauntingEcho** [comment]
for what it's worth - I'd recommend first pinning mocha, then merging the other pull requests & publishing a non-breaking updated version, then dropping the unsupported node versions as a breaking change.

**Comment by iamcdonald** [comment]
Yeah, that sounds like a fair move. I was more trying to gauge whether anyone was actually manning the repo as it seems there are a backlog of PR’s building up. I just choose to comment on this thread as it seems like this is a pre-requisite (having the tests actually run) for dealing with the other outstanding PR’s.

**Comment by hauntingEcho** [comment]
subsumed by https://github.com/auth0/node-xml-encryption/pull/41
