### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [auth0/node-xml-encryption#39]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature,

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by hauntingEcho** [comment]
it looks like that library requires node v4, so using either this library or the literal templates directly would be blocked by #35 

source: http://node.green/

**Comment by gkwang** [comment]
Changes to use native template literals merged here: https://github.com/auth0/node-xml-encryption/pull/59
