### ISSUE TITLE
Update xpath to fix licensing

### ISSUE THREAD

**Issue by wickedest** [auth0/node-xml-encryption#43]
The version of xpath that xml-encryption is currently using (0.0.24) has a CC-BY-SA-2.0 license. IANAL but the license https://creativecommons.org/licenses/by-sa/2.0 reads that xml-encryption would be a "built upon the material" and should have the same license.

xpath changed their license to MIT, made a number of fixes/improvements, and is currently at version 0.0.27.  I'll submit a PR.

**Comment by locnguyen** [comment]
I think this is really important to get in quickly. Some orgs can't use libraries because of the license. In this case a dependency has a license that's the problem. Can this get approved and merged?

**Comment by josecolella** [comment]
I agree. This is essential for our organization, as it is being flagged by our security software

**Comment by johngwilkinson** [comment]
This is essential for us. Is there any blocker to merging the fix that we might be able to help with?

**Comment by johngwilkinson** [comment]
Some more detail: we would like to use https://github.com/auth0/node-samlp, which uses https://github.com/auth0/node-saml, which uses this repo. All of these claim MIT licensing, I believe, but we do not feel confident in this without the newer xpath version here.

**Comment by locnguyen** [comment]
I wonder if anyone at auth0 knows about this issue. It's getting flagged by a lot of scanning software. And I'm sure security minded auth0 customers are seeing this too.

**Comment by neverendingqs** [comment]
I've commented on Auth0's community: https://community.auth0.com/t/licensing-issues-with-node-xml-encryption/12016.

No responses so far.

**Comment by josecolella** [comment]
@neverendingqs The repository also hasn't been touched since February, is there anyone we can reach out to?

**Comment by manometer114** [comment]
We're having the same issue...for us, it's the "SA" portion of the license which poses legal risk, so MIT is much needed.  I'm using passport-saml which uses this, which uses xpath with the CC-BY-SA-2.0 license...

**Comment by radekk** [comment]
New version v0.11.2 was released.

**Comment by neverendingqs** [comment]
Thanks @radekk. Are you able to merge https://github.com/auth0/node-saml/pull/48 and create a release for `saml` as well? `saml` is affected by the same licensing issue.

**Comment by radekk** [comment]
@neverendingqs Working on that one as well 👍
