### ISSUE TITLE
Remove/disable Insecure Algorithms

### ISSUE THREAD

**Issue by cjbarth** [auth0/node-xml-encryption#45]
According to https://csrc.nist.gov/News/2017/Update-to-Current-Use-and-Deprecation-of-TDEA, 3DES is insecure. It should therefore be removed as supported, or we should be able to pass a flag saying that we want to fail on decrypting 3DES. Would a PR be welcome for such a change? If so, which option?

**Comment by esarafianou** [comment]
Fixed in #58. A `disallowInsecureEncryptionAlgorithm` is now supported in version `0.13.0`.
