### ISSUE TITLE
Error: Cannot find module 'xmlenc'

### ISSUE THREAD

**Issue by kevinlbatchelor** [auth0/node-xml-encryption#46]
seems like the build is missing something in node modules to make it work, im using npm 6.1, but node can't seem to resolve the require link

var xmlenc = require('xmlenc');

**Comment by kevliao** [comment]
using var xmlenc = require('xml-encryption');  seems to work.
Are you finding that nothing else works though?  I'm not getting any output calling xmlenc.encrypt().  Their posted sample code doesn't work at all.

**Comment by esarafianou** [comment]
This was an error in the README.md file. To import the module: `var xmlenc = require('xml-encryption');`
The sample in README has now been fixed.
