### ISSUE TITLE
`disallowInsecureDecryptionAlgorithm` vs. `disallowDecryptionWithInsecureAlgorithm`

### ISSUE THREAD

**Issue by cjbarth** [auth0/node-xml-encryption#63]
### Description

The tests and documentation mention using `disallowInsecureDecryptionAlgorithm` to disable the use of insecure algorithms to decrypt, however, the source code seems to only reference `disallowDecryptionWithInsecureAlgorithm`. Which of these is correct?

`disallowInsecureDecryptionAlgorithm`:
https://github.com/auth0/node-xml-encryption/search?q=disallowInsecureDecryptionAlgorithm&unscoped_q=disallowInsecureDecryptionAlgorithm

`disallowDecryptionWithInsecureAlgorithm`:
https://github.com/auth0/node-xml-encryption/search?q=disallowDecryptionWithInsecureAlgorithm&unscoped_q=disallowDecryptionWithInsecureAlgorithm

**Comment by gkwang** [comment]
The latter is correct; thanks for catching it.

**Comment by cjbarth** [comment]
@gkwang Did you want me to replace all instances of `disallowInsecureDecryptionAlgorithm` with `disallowDecryptionWithInsecureAlgorithm` and make a PR?
