### ISSUE TITLE
Could you please release a version 1.2.3 with the lastest commit to NPM

### ISSUE THREAD

**Issue by forty** [auth0/node-xml-encryption#82]
This fixes a vulnerability in the xmldom dependency. Thanks

**Comment by jupenur** [comment]
Just dropping in to say node-xml-encryption isn't affected. I discovered the original vulnerability and it only impacts fairly specific use-cases.

**Comment by forty** [comment]
Yes, that was my understanding as well, but `npm audit` will scream if you depend on a vulnerable package regardless of whether the vulnerability is actually impacting or not.

Looks like 1.2.3 has been released with the module update, closing :heavy_check_mark:
