### ISSUE TITLE
xmldom dependency fails NPM audit (Advisory 1769)

### ISSUE THREAD

**Issue by lucioperca** [auth0/node-xml-encryption#87]
Note that the relevant update isn't published yet: https://github.com/xmldom/xmldom/issues/271

### Description

A potential vulnerability is currently present in the xml-encryption package: https://www.npmjs.com/package/xml-encryption

Currently, the package has a dependency on xmldom 0.6.0. NPM has a security advisory for this version, with a recommendation to upgrade to version 0.7.0 to fix the problem: https://www.npmjs.com/advisories/1769

I've been informed by your team that this issue lacks a demonstrated security impact on the xml-encryption package itself (and consequently won't be resolved by submitting the issue through your private security channels), so I assume the appropriate action on my part is to log it here as a general CI issue introduced into any dependent projects instead.

### Reproduction

From the command line in the xml-encryption repo, run either `npm audit` or `yarn audit`. Bothe report the above advisory.

### Environment

Version 1.2.4

**Comment by RopoMen** [comment]
More information about xmldom npm publish, https://github.com/xmldom/xmldom/discussions/270

**Comment by forty** [comment]
See https://github.com/auth0/node-xml-encryption/pull/88

**Comment by LoneRifle** [comment]
Duplicate of #88
